# Generated by Django 3.1.1 on 2020-10-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group_messages', '0002_auto_20201002_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
