# Generated by Django 3.1.1 on 2020-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group_messages', '0003_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
